
= StreamServer

Simple file server written in (safe) Rust, which allows access to incomplete files, sending new bytes when they are received.

== Structure

Files are stored in a broadcast channel, where original a clone of the original receiver is always created, keeping the original pointing at the beginning of the file. Naturally, this method of storage is volatile and all data is wiped on program shutdown.

Using broadcast channel has the limitation that it imposes restriction on number of parts of the file. In the default configuration the program allocates space for 2^20 parts for each file (taking up about 24 MiB per file) and collects chunks of the body into parts of at least 1 MiB, theoretically limiting size of an individual file to around 1 TiB.

== Development

I originally tried implementing my own structure that would grow as necessary, and thus not have any file size limitations at all (it was based on singly linked list). While it initially seemed to work when testing with `producer.rs`/`consumer.rs`, during unit testing I noticed it had issues with synchronization, which I ultimately couldn't figure out how to fix.

This lead me to turn to broadcast channels, more specifically the `async-broadcast` library which provides bounded broadcast channel. This library seems to be reasonably tested, well liked, frequently updated, and written only using safe Rust.

== Running StreamServer

Assuming `cargo` is installed on the system, server can be run using `cargo run --release --bin server`.

Similarly producer and consumer can be run using `cargo run --release --bin producer` and `cargo run --release --bin consumer` respectively.

Tests can be run using `cargo test`.

