
= StreamServer

Simple file server written in (safe) Rust, which allows access to incomplete files, sending new bytes when they are received.

image::https://github.com/sdasda7777/StreamServer/actions/workflows/rust.yml/badge.svg[]

== Structure

Files are stored in a broadcast channel, and a clone of the original receiver is always created, keeping the original pointing at the beginning of the file. Naturally, this method of storage is volatile and all data is wiped on program shutdown.

Using broadcast channel has the limitation that it imposes restriction on number of parts of the file. In the default configuration the program allocates space for 2^20 parts for each file (taking up about 24 MiB per file) and collects chunks of the body into parts of at least 1 MiB, theoretically limiting size of an individual file to around 1 TiB.

== Development

I originally tried implementing my own structure that would grow as necessary, and thus not have any file size limitations at all (it was initially based on array, later on singly linked list). While it initially seemed to work when testing with `producer.rs`/`consumer.rs`, during unit testing I noticed it had issues with synchronization, which I ultimately couldn't figure out how to fix, and even if I could, I wasn't confident I could test it properly.

This lead me to turn to broadcast channels, more specifically the `async-broadcast` library which provides bounded broadcast channel. This library seems to be reasonably tested, well liked, frequently updated, and written only using safe Rust.

== Running StreamServer

Assuming `cargo` is installed on the system, server can be run using `cargo run --release --bin server`. For benchmark purposes, server accepts numeric arguments `--file-allocated-blocks` and `--file-block-size` which control number of blocks each file allocates and preferred size of a single block respectively. For example: `cargo run --release --bin server -- --file-allocated-blocks 8 --file-block-size 1024` allocates for each file 8 blocks and pushes a (non-last) block after it surpasses 1024 bytes. As mentioned, default value for both arguments is 2^20.

Similarly producer and consumer can be run using `cargo run --release --bin producer` and `cargo run --release --bin consumer` respectively.

Tests can be run using `cargo test`.
